services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    volumes:
      - .:/var/www/html
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    entrypoint: ["sh", "docker/entrypoint.sh"]
    env_file:
      - .env
